name: Update Visitor Count

on:
  workflow_dispatch:

jobs:
  update-count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read current visitor count
      id: read_count
      run: |
        count=$(cat project-files/folder1/visitors.txt)
        echo "Current count: $count"
        echo "::set-output name=count::$count"

    - name: Increment visitor count
      id: increment_count
      run: |
        new_count=$(( ${{ steps.read_count.outputs.count }} + 1 ))
        echo "New count: $new_count"
        echo "::set-output name=new_count::$new_count"

    - name: Update visitors.txt
      run: |
        echo "${{ steps.increment_count.outputs.new_count }}" > project-files/folder1/visitors.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add project-files/folder1/visitors.txt
        git commit -m "Update visitor count to ${{ steps.increment_count.outputs.new_count }}"
        git push
